[workspace]
members = [
    "./3rdparty/tvm/3rdparty/tvm-ffi/rust/tvm-ffi",
    "./3rdparty/tvm/3rdparty/tvm-ffi/rust/tvm-ffi-sys",
    "./3rdparty/tvm/3rdparty/tvm-ffi/rust/tvm-ffi-macros",
    "./tvm-runtime",
    "./tvm-runtime-sys"
]
resolver = "2"
